### ISSUE TITLE
How to use it with ActiveForm Model Field?

### ISSUE THREAD

**Issue by ghost** [petrgrishin/yii2-array-field#1]
I am using PostgreSQL and I have column sites (type JSONB) which stores website, fb, tw, and g+ urls in JSON object form.

My form code is as below:

```
<?= $form->field($model, 'siteArray[website_url]')->textInput()->label('Website') ?>

<?= $form->field($model, 'siteArray[facebook_url]')->textInput()->label('Facebook') ?>

<?= $form->field($model, 'siteArray[twitter_url]')->textInput()->label('Twitter') ?>

<?= $form->field($model, 'siteArray[google_plus_url]')->textInput()->label('Google Plus') ?>
```

And I have set behavior as below:

```
public function behaviors()
{
    return [
        'siteArray' => [
            'class' => ArrayAccessFieldBehavior::className(),
            'fieldNameStorage' => 'sites',
        ]
    ];
}
```

But it is not working. It is not storing any data in "sites" attribute. Can you tell what am I missing or doing wrong?

**Comment by petrgrishin** [comment]
Hello!
ArrayField is responsible for storing an array of data in the table model.

You need access to extra attribute model, a project which uses ArrayField — https://github.com/petrgrishin/yii-extra-attributes

Now you can spy on the implementation here https://github.com/petrgrishin/yiiapp-framework/blob/master/src/Yiiapp/Framework/Model/ActiveRecord.php#L74

**Comment by petrgrishin** [comment]
Closed. Timed out
